// <auto-generated />
using System;
using JobInfrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobInfrastructure.DataAccess.Migrations
{
    [DbContext(typeof(JobContext))]
    partial class JobContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JobDomain.AgreegateModels.JobAgreegate.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DateDeleted")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("JobStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("JobStatusId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobDomain.AgreegateModels.JobAgreegate.JobStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("JobStatus", (string)null);
                });

            modelBuilder.Entity("JobDomain.AgreegateModels.JobAgreegate.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DateDeleted")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Input")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAsync")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("Output")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("StructTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("StructTypeId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("JobDomain.AgreegateModels.JobAgreegate.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DateDeleted")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Instruction")
                        .HasColumnType("longtext");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int?>("OrderOperationNumber")
                        .HasColumnType("int");

                    b.Property<string>("Output")
                        .HasColumnType("longtext");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecificationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StepStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("StepStatusId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("JobDomain.AgreegateModels.JobAgreegate.StepStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("StepStatus", (string)null);
                });

            modelBuilder.Entity("JobDomain.AgreegateModels.JobAgreegate.StructType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("StructTypes", (string)null);
                });

            modelBuilder.Entity("JobDomain.AgreegateModels.JobAgreegate.Job", b =>
                {
                    b.HasOne("JobDomain.AgreegateModels.JobAgreegate.JobStatus", "JobStatus")
                        .WithMany()
                        .HasForeignKey("JobStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobStatus");
                });

            modelBuilder.Entity("JobDomain.AgreegateModels.JobAgreegate.Operation", b =>
                {
                    b.HasOne("JobDomain.AgreegateModels.JobAgreegate.Job", "Job")
                        .WithMany("Operations")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobDomain.AgreegateModels.JobAgreegate.StructType", "StructType")
                        .WithMany()
                        .HasForeignKey("StructTypeId");

                    b.Navigation("Job");

                    b.Navigation("StructType");
                });

            modelBuilder.Entity("JobDomain.AgreegateModels.JobAgreegate.Step", b =>
                {
                    b.HasOne("JobDomain.AgreegateModels.JobAgreegate.Operation", null)
                        .WithMany("Steps")
                        .HasForeignKey("OperationId");

                    b.HasOne("JobDomain.AgreegateModels.JobAgreegate.StepStatus", "StepStatus")
                        .WithMany()
                        .HasForeignKey("StepStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StepStatus");
                });

            modelBuilder.Entity("JobDomain.AgreegateModels.JobAgreegate.Job", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("JobDomain.AgreegateModels.JobAgreegate.Operation", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
